### ISSUE TITLE
Fortsetztung der Artikelreihe

### ISSUE THREAD

**Issue by jk-propeller** [Netzberufler/themecoder-block#1]
Guten Tag,

ich bin vor einigen Tagen über Ihre Artikelreihe zum Theme Blockerstellung gestolpert. Ich habe schon länger eine verständliche Anleitung zu diesem Thema gesucht. Meist wird leider nur ein Code gezeigt der dann aber nicht weiter erklärt wird. Genau das machen Sie anders!
Ich finde es richtig toll von Ihnen das Sie auf die einzelnen Zeilen eingegangen sind und auch Dinge wie "destructuring" angeschnitten haben. Das hat mir sehr viel geholfen, da ich ein Mensch bin der die Sachen auch versehen will um Sie dann nachher selbst besser anwenden zu können. Nun bin ich mit dem 4. Teil durch und wollte fragen ob Sie planen die Reihe in naher Zukunft weiter zu führen? 

Es würde mich und bestimmt auch einige andere Anfänger sehr freuen zu erfahren wie man die InspectorControls einbaut etc.

Da ich auf der unter dem Artikel keine Kommentarsektion gefunden habe (evtl. bin ich auch einfach blind^^) dachte ich ich versuche es mal mit einem issue hier.

**Comment by Netzberufler** [comment]
Hallo,

Vielen Dank für das tolle Feedback und lesen meiner Tutorials. Momentan fehlt mir etwas die Zeit, die Serie fortzuführen und ich bin nicht aktiv am Bloggen, sorry. 

Die Kommentare sind immer die ersten Monate offen und werden dann automatisch geschlossen, werden sonst einfach zu viele :)

LG,
Thomas
